#! /bin/sh
# /etc/init.d/display_screen

### BEGIN INIT INFO
# Provides:          display_screen
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# I got this example from: http://www.stuffaboutcode.com/2012/06/raspberry-pi-run-program-at-start-up.html
# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting display_screen"
    # run application you want to start
    ~pi/Adafruit_Python_SSD1306/examples/jay_display.py &
    ;;
  stop)
    echo "Stopping display_screen"
    # kill application you want to stop
    killall jay_display.py
    ;;
  *)
    echo "Usage: /etc/init.d/display_screen {start|stop}"
    exit 1
    ;;
esac

exit 0

